apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-{{ .Values.namespaceSuffix }}-docker-secret
  namespace: {{ .Values.project }}-{{ .Values.namespaceSuffix }}-namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig | toString | b64enc | quote }}
