---
- name: Use of roles on the host
  hosts: all
  become: true

  tasks:
    - name: Run roles on hosts
      include_role:
        name: "{{ role_item }}"
      loop: "{{ roles }}"
      loop_control:
        loop_var: role_item