---
- name: install grafana loki docker driver
  ansible.builtin.shell: |
    docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
    systemctl restart docker
